<a href="https://colab.research.google.com/github/Ale-mini/1822-Almacenando-Datos-En-El-Navegador/blob/projectoInicial/Copia_de_Untitled7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
pd.set_option('display.max_rows', 100)
pd.set_option('display.max_columns', 10)

In [ ]:
dataset = pd.read_csv('dat-2.csv' , sep = ';')
dataset

     ano         mes  altas  bajas
0   2015       enero     40     19
1   2015     febrero     39     31
2   2015       marzo     62     18
3   2015       abril     30     30
4   2015        mayo     41     23
5   2015       junio     49     24
6   2015       julio     35     28
7   2015      agosto     36     26
8   2015  septiembre     43     25
9   2015     octubre     45     26
10  2015   noviembre     49     22
11  2015   diciembre     27     34
12  2016       enero     19     28
13  2016     febrero     27     32
14  2016       marzo     36     28
15  2016       abril     46     35
16  2016        mayo     33     26
17  2016       junio     36     27
18  2016       julio     32     36
19  2016      agosto     32     36
20  2016  septiembre     40     34
21  2016     octubre     45     34
22  2016   noviembre     42     23
23  2016   diciembre     38     38
24  2017       enero     32     30
25  2017     febrero     23     40
26  2017       marzo     85     37
27  2017       abril     62     28
28  2017        mayo     77     27
29  2017       junio    131     26
30  2017       julio     90     24
31  2017      agosto     89     27
32  2017  septiembre    133     36
33  2017     octubre     65     27
34  2017   noviembre    115     16
35  2017   diciembre     50     15
36  2018       enero     60     24
37  2018     febrero     14     42
38  2018       marzo     60     29
39  2018       abril     54     40
40  2018        mayo     86     31
41  2018       junio     18     37
42  2018       julio     27     14
43  2018      agosto     50     29
44  2018  septiembre     42     33
45  2018     octubre     40     22
46  2018   noviembre     39     28
47  2018   diciembre     26     19
48  2019       enero     35     32
49  2019     febrero     20     34
50  2019       marzo     50     40
51  2019       abril     18     34
52  2019        mayo     70     22
53  2019       junio     18     23
54  2019       julio     28     46
55  2019      agosto      8     28
56  2019  septiembre     26     40
57  2019     octubre     39     18
58  2019   noviembre     15     18
59  2019   diciembre     19     29
60  2020       enero     25     31
61  2020     febrero     29     18
62  2020       marzo     18     21
63  2020       abril      4     33
64  2020        mayo     23     22
65  2020       junio     23     16
66  2020       julio     35     20
67  2020      agosto     35     34
68  2020  septiembre     34     20
69  2020     octubre     29     24
70  2020   noviembre     43     23
71  2020   diciembre      5     24
72  2021       enero     47     12
73  2021     febrero     29     24
74  2021       marzo     43     18
75  2021       abril     41     26
76  2021        mayo     25     22
77  2021       junio     25     19
78  2021       julio     29     26
79  2021      agosto     34     29
80  2021  septiembre     21     16
81  2021     octubre     30     18
82  2021   noviembre     26     17
83  2021   diciembre     23     83
84  2020       enero     20     18
85  2020     febrero     23     28
86  2020       marzo     21     25
87  2020       abril     71     10
88  2020        mayo     29     23
89  2020       junio     26     20
90  2020       julio     29     26
91  2020      agosto     34     29
92  2020  septiembre     21     16
93  2020     octubre     30     18
94  2020   noviembre     26     17
95  2020   diciembre     23     83

In [ ]:
dataset.dtypes

ano       int64
mes      object
altas     int64
bajas     int64
dtype: object

In [ ]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   ano     96 non-null     int64
 1   mes     96 non-null     object
 2   altas   96 non-null     int64
 3   bajas   96 non-null     int64
dtypes: int64(3), object(1)
memory usage: 3.1+ KB